galaxy_info:
  author: Rémi Duraffort
  description: LAVA
  company: Linaro
  issue_tracker_url: https://git.lavasoftware.org/lava/pkg/ansible/issues
  license: GPLv2
  min_ansible_version: 2.4
  platforms:
  - name: Debian
    versions:
    - stretch

  galaxy_tags: []

dependencies: []
