- name: Install OS dependencies
  apt:
    pkg: [
      'gpg',
      'postgresql',
      'apache2'
    ]
    state: latest
    update_cache: yes
  tags:
    - install

- name: Ensure LAVA deb archive signing keys are installed.
  apt_key:
      id: "{{ lava_apt_key_id }}"
      url: "{{ lava_apt_key_url }}"
      state: present
  when: lava_apt_key_id is defined and lava_apt_key_url is defined

- name: Ensure LAVA apt source repository is present.
  apt_repository:
    repo: "{{ lava_apt_repo }}"
    state: present
  when: lava_apt_repo is defined

- name: Ensure LAVA and dependencies are installed.
  apt:
    update_cache: yes
    name:
    - lava-server={{ lava_version }}
    # Following is not strictly required, but handy to have docs matching with
    # the current version directly inside the local instance.
    - lava-server-doc={{ lava_version }}
    # Required for LAVA MultiNode jobs only.
    - lava-coordinator
    state: present
    install_recommends: no

- name: Deploy LAVA logger settings.
  template:
    src: ./templates/lava-logs.j2
    dest: "{{ lava_srv_conf_dir }}/lava-logs"
    mode: u=rw,g=r,o=r

- name: Deploy LAVA master settings.
  template:
    src: ./templates/lava-master.j2
    dest: "{{ lava_srv_conf_dir }}/lava-master"
    mode: u=rw,g=r,o=r
  notify: restart lava-master

- name: Deploy LAVA coordinator config for MultiNode jobs.
  template:
    src: ./templates/lava-coordinator.conf.j2
    dest: "{{ lava_coordinator_conf_dir }}/lava-coordinator.conf"
    mode: u=rw,g=r,o=r
  notify: restart lava-coordinator

- name: Deploy LAVA server settings.
  template:
    src: ./templates/lava-server-settings.conf.j2
    dest: "{{ lava_srv_conf_dir }}/settings.conf"
    mode: 0640
    owner: "lavaserver"
#  notify: "restart LAVA services"

- name: Ensure LAVA services are started.
  service:
    state: restarted
    name: "{{ item }}"
  with_list:
  - lava-publisher
  - lava-coordinator
  - lava-server-gunicorn

- name: Enable the Apache2 modules
  community.general.apache2_module:
    state: present
    name: proxy
    name: proxy_http

- name: a2ensite lava-server
  command: a2ensite lava-server

- name: a2dissite default
  command: a2dissite 000-default

- name: Ensure Apache2 restarted
  service:
    state: restarted
    name: apache2
